from __future__ import annotations

from tests.integration import test_brightdata_adapter_collection as collection
from tests.integration import test_brightdata_adapter_router_basics as router_basics
from tests.integration import test_brightdata_adapter_router_windows as router_windows

test_adapter_declares_only_normal_posts_operation = (
    collection.test_adapter_declares_only_normal_posts_operation
)
test_collection_preserves_all_safe_platform_posts = (
    collection.test_collection_preserves_all_safe_platform_posts
)
test_mixed_returned_account_aborts_without_partial_batch = (
    collection.test_mixed_returned_account_aborts_without_partial_batch
)
test_accepted_snapshot_failure_propagates_without_retrigger = (
    collection.test_accepted_snapshot_failure_propagates_without_retrigger
)
test_adapter_collect_returns_complete_router_outcome = (
    collection.test_adapter_collect_returns_complete_router_outcome
)
test_schema_failure_maps_to_abort_without_diagnostics_canaries = (
    collection.test_schema_failure_maps_to_abort_without_diagnostics_canaries
)
test_empty_source_set_is_rejected_before_client_creation = (
    router_basics.test_empty_source_set_is_rejected_before_client_creation
)
test_public_runtime_preserves_all_post_types_through_router = (
    router_basics.test_public_runtime_preserves_all_post_types_through_router
)
test_router_preserves_each_account_collection_window = (
    router_windows.test_router_preserves_each_account_collection_window
)
test_conflicting_duplicate_collection_windows_fail_before_provider_io = (
    router_windows.test_conflicting_duplicate_collection_windows_fail_before_provider_io
)
test_equivalent_duplicate_collection_windows_deduplicate = (
    router_windows.test_equivalent_duplicate_collection_windows_deduplicate
)
test_inverted_collection_window_fails_typed_before_provider_io = (
    router_windows.test_inverted_collection_window_fails_typed_before_provider_io
)
